CERT-Polska/drakvuf-sandbox

- drakcore/package/build.sh
- drakrun/package/build.sh
* revert `BASE_IMAGE` to Debian Buster in both packages
* make it configurable through env variable
Turns out it doesn't actually work cross-distribution :thinking:
> Revert base image back to Debian Buster and make it configurable

- LICENSE
- drakcore/debian/changelog
- drakcore/drakcore/frontend/package-lock.json
- drakcore/drakcore/frontend/package.json
- drakcore/drakcore/frontend/src/App.js
- drakcore/setup.py
- drakrun/debian/changelog
- drakrun/setup.py
* Bump to 0.2.0 before release
* Fix year range for DRAKVUF Sandbox copyright (`2020` -> `2019-2020`)
> Bump version to 0.2.0

- drakcore/debian/drakcore.links
- drakcore/debian/postinst
- drakcore/debian/prerm
- drakcore/drakcore/app.py
- drakcore/drakcore/bin/drak-postprocess
- drakcore/drakcore/frontend/src/api/index.js
- drakcore/drakcore/postprocess/__init__.py
- drakcore/drakcore/postprocess/pstree.py
- drakcore/drakcore/process.py
- drakcore/drakcore/systemd/drak-postprocess.service
- drakcore/drakcore/tests/test_process_tree.py
- drakcore/setup.py
- test/test_sanity.py
closes #71 
Moved the post processing into drakrun as karton Consumer.
The only thing left is to decide how we would like to run it. By adding another daemon? :thinking:
> Add karton-based analysis post processing

- drakrun/drakrun/draksetup.py
Looks like some drivers are not properly installed in Windows 10 when there is low disk space. We use either qcow2 or zfs which both can overbook space so there is no problem with disk being virtually large though.
> Bump default disk size to 100 GB

- drakcore/drakcore/app.py
When [analysis]/metadata.json object is missing, /list endpoint will
fail due to incorrect handling of exception.
The code tries to use minio.error.NoSuchKey exception, however the
exception object is imported as NoSuchKey and minio refers to Minio
client object.
closes #144
> Fix exception handling in /list endpoint

- README.md
- drakrun/drakrun/scripts/cfg.template
OK, so after a lot of debugging we have to add two lines in VM configuration file.
CPUID one disables hyperthreading support flag and VGA changes driver from cirrus to stdvga which is currently recommended by QEMU developers.
closes #149
> drakrun/configs: Fix running Windows with nested KVM

- drakrun/drakrun/draksetup.py
When max_vms isn't specified during installation it defaults to
1 - an integer. Otherwise it becomes a string, which forces the code
to explicitly cast the string to the integer (or break, in case of drak-healthcheck).
> Make max_vms install variable consistent and an integer

- drakrun/drakrun/storage.py
We can overprovision ZFS block device to present large disk to Windows and use smaller disk under the hood
> storage: ZFS: Use sparse vm-0 volume

- README.md
Don't use `sudo`, as some installations might not have it. Use $/# notation to indicate privileged shell.
Add privileged marking where they were missing
> Remove sudo from README commands, use #/$ notation

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/AnalysisMain.js
- drakcore/drakcore/frontend/src/api/index.js
I believe it's nice to have sample hash visible in AnalysisMain view. I will be happy to change the position of this component if our user experience team decides so.
> Sample hash in AnalysisMain view

- drakcore/package/Dockerfile
- drakrun/package/Dockerfile
Ok, so release 1.2.1 of dh-virtualenv is already in Debian repositories, so we may use it.
(TODO: test ubuntu 18/20 before merging)
> Change dh-virtualenv to debian-built version

- drakcore/drakcore/app.py
- drakrun/drakrun/drakpush.py
- drakrun/drakrun/main.py
Drakrun expects that the extension is passed in task header. I've also moved `timeout`, `start_command` and `override_uid` from task_resources to task_payload as this is what drakrun expects.
> Added extensions to drakcore and drakpush.

- README.md
- drakrun/drakrun/draksetup.py
- drakrun/requirements.txt
`click` provides cleaner approach for building CLIs :)
One breaking change:
```
draksetup install [ISO_PATH]
```
instead of 
```
draksetup install --iso
```
providing ISO file is mandatory so we might as well parse it as an argument to the command
> Use click for draksetup CLI

- drakcore/drakcore/app.py
- drakcore/drakcore/postprocess/logindex.py
We cannot simply load gigabyte-size logs into browser. To fix this,
generate index for each log to quickly look up were n-th line starts.
Also add the ability to download a chunk of log file from API.
> Add log index generation after analysis

- drakcore/drakcore/frontend/src/AnalysisMain.js
Strip process file paths, to reduce noise.
Display metadata side-by-side with process tree.
Rename Sha256 -> SHA256
Preview:
> Main analysis view fix

- drakrun/drakrun/draksetup.py
Should fix:
```
Traceback (most recent call last):
File "/root/drakvuf-sandbox/venv/bin/draksetup", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/root/drakvuf-sandbox/drakrun/drakrun/py-scripts/draksetup", line 5, in <module>
ds.main()
File "/root/drakvuf-sandbox/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/root/drakvuf-sandbox/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/root/drakvuf-sandbox/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/root/drakvuf-sandbox/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, …
```
> Fix invalid argument in draksetup postinstall

- drakrun/drakrun/draksetup.py
Added wrapper over complex `xl qemu-monitor-command change` instruction.
Issue: #171 
I couldn't find information regarding the device number. We rely on hard coded `5632` index. Is that ok, or should be parse output of: `xl qemu-monitor-command "info block"`?
The example output of `info block`:
```bash
$ xl qemu-monitor-command vm-1 "info block"
ide0-hd0 (#block191): /home/k/dev/var/lib/drakrun/volumes/vm-1.img (qcow2)
Attached to:      /machine/unattached/device[13]
Cache mode:       writeback
Backing file:     /var/lib/drakrun/volumes/vm-0.img (chain depth: 1)
ide-5632 (#block530): /home/k/dev/drakvuf-packages/win-iso/SW_DVD5_Win_Pro_7w_SP1_64BIT_Polish_-2_MLF_X17-59386.ISO (raw, read-only)
Attached to:      /machine/unattached/device[14]
Removable device: not locked, tray closed
Cache …
```
> Implement mount command in draksetup

- drakcore/drakcore/process.py
- drakrun/drakrun/main.py
This patch adds drakrun and drak-postprocess logs for each analysis
in Minio. This allows for easier debugging as the logs can be viewed
directly in browser instead of SSHing into the server.
Currently, we have no shared code between drakrun and drakcore so some
of the changes are duplicated.
> Store drakrun/drak-postprocess logs in Minio

- drakrun/drakrun/scripts/cfg.template
Guest option 'builder' is deprecated. Replace it with 'type'.
See:
https://xenbits.xen.org/docs/4.14-testing/man/xl.cfg.5.html#Deprecated-guest-type-selection
> Update VM config template

- .drone.yml
- ci/build_bundle.sh
We're relying on externally hosted debs of drakvuf-bundle. This patch
intergates the build process with our CI. This ensures that updated
drakvuf submodule can be built correctly and enables further
enhancements in the future.
> Integrate drakvuf-bundle building with CI infrastracture

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/UploadSample.js
Solves:  #237 
It's now possible to upload files with filenames containing dots and dashes. For example: `invoice.pdf.exe`, `sample-1.exe`.
> More liberal regex check for uploaded filenames

- .drone.yml
- ci/packer/.gitignore
- ci/packer/build_vm.sh
- ci/packer/install_zfs.sh
- ci/packer/preseed.cfg
- ci/packer/vmbase.json
closes #107
Some additional plumbing is required to use the image during testing, this might come in further PR.
> ci: Build Debian-based images with preinstalled drakvuf-bundle

- drakcore/drakcore/frontend/src/AnalysisList.js
In some circumstances, the analysis bucket might contain invalid/corrupted/missing data. This shouldn't break analysis list completely (now: it does).
When there is any folder with missing metadata in the analysis result bucket:
```
Uncaught (in promise) RangeError: Invalid time value
at Date.toISOString (<anonymous>)
at a.value (AnalysisList.js:23)
at AnalysisList.js:56
at Array.map (<anonymous>)
at a.value (AnalysisList.js:47)
at Fa (react-dom.production.min.js:182)
at Xa (react-dom.production.min.js:181)
at df (react-dom.production.min.js:263)
at ol (react-dom.production.min.js:246)
at fl (react-dom.production.min.js:246)
```
> Fix bug in AnalysisList.js

- drakcore/drakcore/app.py
resolve #266
Avoid returning half-empty objects from drak-web backend's `/list` endpoint, so we don't have glitchy entries in the analysis list UI.
> drakcore: don't display broken analyses in the web UI

- drakrun/drakrun/draksetup.py
Modify `draksetup mount` invocation to match the docs:
https://github.com/CERT-Polska/drakvuf-sandbox/blob/master/docs/usage/getting_started.rst
> Extra software: At this point you might optionally install additional software. You can execute:
> `# draksetup mount /path/to/some-cd.iso`
> draksetup mount: allow to use non-absolute path, default to vm-0

- drakrun/drakrun/main.py
Disable plugins that are reducing stability at the moment:
* `dkommon` - causes hang of Windows 10 2004, needs inspection in future;
* `envmon` - in some circumstances causes DRAKVUF not being able to start (some hooks required by the plugin can not be applied and there is no fallback);
> Block plugins introducing instability: dkommon, envmon

- docs/usage/getting_started.rst
Sometimes behavioral logs get spammed with `mscorsvw.exe` process (compilation of .NET images), add an optional step in "getting started" that helps to prevent this.
> Add information about .NET Framework cache generation

- drakrun/drakrun/config.dist.ini
We check for key `identity`, not `instance`:
https://github.com/CERT-Polska/drakvuf-sandbox/blob/d91731ec1cc55ac9f17b1cd6c4c4a1983bdcf757/drakrun/drakrun/main.py#L619
> fix bug in config.dist.ini (instance)

- drakcore/drakcore/app.py
- drakcore/drakcore/database.py
- drakcore/drakcore/postprocess/cacheupdate.py
Instead of asking MinIO every time someone requests a list of metadata,
load them directly from the local database. This significantly speeds up
the requests, however introduces additional obstacle - how to populate
the local cache. Solve this by abusing the postprocess service - trigger a
request for metadata on a newly received analysis.
> drakcore: Load analysis list from cache

- drakrun/drakrun/injector.py
Local variable `cmd` shadows `cmd` function argument, causing bug.
> drakrun: fix injector.py bug with variable shadowing

- drakcore/drakcore/postprocess/__init__.py
- drakcore/drakcore/postprocess/ipt_disasm.py
- drakcore/drakcore/postprocess/ipt_utils.py
- drakcore/drakcore/postprocess/log_index.py
- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/injector.py
- drakrun/drakrun/main.py
- drakrun/drakrun/scripts/cfg.template
drakvuf-bundle must be built from branch https://github.com/CERT-Polska/drakvuf/tree/sandbox-ipt-work and ran on a processor which supports IPT
Currently, the stub is able to run `ptxed` and report how many lines there were in disassembly.
> Add stub of optional IPT support

- drakcore/drakcore/app.py
When iterating over tasks it might happen, that we try to load
a task which was already cleaned up. In this case, skip it.
> drakcore: Handle missing key in /status

- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
* Refactor `analysis_uid` into property helper function.
* Add `use_root_uid` in `drakrun` section of `config.ini` to let user decide that all analyses should be stored under their root_uids instead of the actual task uids. This is more user friendly but obviously doesn't let to run DRAKVUF Sandbox more than once within a single task tree. I think this is a fair deal.
* We are going to set `use_root_uid=1` in prod.
> Add "use_root_uid" config setting to preserve compatibility with pre-OSS

- drakcore/package/Dockerfile
- drakrun/package/Dockerfile
* `dh-virtualenv` debian package that we were hotlinking was recently removed, thus breaking package build process entirely
* `dh-virtualenv` is now present on all supported distributions, so we might install it normally through `apt-get`
> Fix dh-virtualenv installation in package build

- drakrun/drakrun/scripts/drak-vnc
this file comes from era when we tried using websockify as vnc instead of qemu builtin feature
> remove old script

- ci/Dockerfile-bundle
- ci/custom_bundle.sh
In some cases, users might want to add custom patches for the DRAKVUF
bundle. Add the ability to easily rebuild the deb by pointing a Docker
image at the repository and a directory with patches.
Current implementation allows only Xen and QEMU patching, however this
can be easily extended in the future.
At first I wanted to reuse existing Dockerfiles in DRAKVUF repository, however they're doing it somewhat differently (compiling during Docker image building, I wanted to avoid that and use static image with build dependencies)
Bundle customization docs will be added in a separate PR
> Add drakvuf-bundle customization

- drakcore/drakcore/postprocess/slice_logs.py
- drakcore/drakcore/process.py
This should resolve #371 
Currently there's no way to easily wait until postprocessing artifacts are generated. 
Fix this by sending a new task after finishing all postprocessing steps.
> Send a task after postprocessing

- drakrun/drakrun/drakpdb.py
For some reason we were missing the most important JSON DLL profile :trollface:
> drakpdb: add WOW's ntdll to the list of DLL profiles

- docs/drakpdb.rst
- docs/index.rst
- drakrun/debian/drakrun.links
- drakrun/drakrun/drakpdb.py
- drakrun/drakrun/py-scripts/drakpdb
- drakrun/setup.py
Argument parsing in drakpdb is completely broken as per now, due to `file` argument being always required and a bug `if` vs `elif` when dispatching commands.
> Fix inconsistent argument parsing in drakpdb, expose it as cmdline tool

- drakrun/drakrun/main.py
Contents of `ipt` directory is not deleted after archived into a zip, thus we upload lots of small files into `ipt/` analysis subdirectory in MinIO. These files are redundant because they are already archived into `ipt.zip`
> drakrun: delete contents of ipt directory when archiving

- drakrun/drakrun/main.py
Fast singlestep is disabled by default due to a bug that causes unexpected behavior when DRAKVUF is ran multiple times against the same VM. We are not affected because we always restore the VM from snapshot anyway :smarts:
Thus we can safely enable fast-singlestep and have faster singlestep.
> drakrun: enable fast singlestep

- drakcore/drakcore/bin/drak-gen-ptxed
- drakcore/drakcore/postprocess/ipt_disasm.py
One command to rule them all.
```
```
and after few minutes it starts printing trace disassembly for vCPU 0 for process CR3=0x23a4c000
> drakcore: improve drak-gen-ptxed

- drakcore/drakcore/analysis.py
- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/AnalysisMain.js
- drakcore/drakcore/postprocess/__init__.py
- drakcore/drakcore/postprocess/wireshark_key_file_gen.py
Generates a file with session keys from tlsmon.log which is acceptable by Wireshark and can be loaded without any modification to decrypt tls traffic.
I'm open to suggestions about improving the design side of this pr.
> drakcore: generate a file with TLS keys in Wireshark format

- drakrun/drakrun/networking.py
We're allowing the possibility of dnsmasq and tcpdump missing from the
system. It's safe to remove it as we're depending on them in Debian
packaging.
> drakrun: Make tcpdump and dnsmasq non optional

- ci/packer/vmbase.json
> ci: Bump Debian ISO to 10.7

- drakrun/drakrun/playground.py
- drakrun/drakrun/py-scripts/drakplayground
- drakrun/requirements.txt
- drakrun/setup.py
Example session:
```
(env) root@xeniarz:~# python drakvuf-sandbox/playground.py
qemu-img: warning: Deprecated use of backing file without explicit backing format (detected format of qcow2)
Formatting '/var/lib/drakrun/volumes/vm-10.img', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=107374182400 backing_file=/var/lib/drakrun/volumes/vm-0.img backing_fmt=qcow2 lazy_refcounts=off refcount_bits=16
Loading new save file /var/lib/drakrun/volumes/snapshot.sav (new xl fmt info 0x3/0x0/1982)
Savefile contains xl domain config in JSON format
Parsing config from /etc/drakrun/configs/vm-10.cfg
xc: info: Found x86 HVM domain from Xen 4.14
xc: info: Restoring domain
xc: info: Restore successful
xc: info: XenStore: mfn 0xfeffc, dom 0, evt 1
xc: info: Console: mfn 0xfefff, dom …
```
> drakrun: Add playground

- drakcore/drakcore/tools/ipt/.clang-format
- drakcore/drakcore/tools/ipt/CMakeLists.txt
- drakcore/drakcore/tools/ipt/ipt-blocks.cpp
Add a tool for extracting executed basic blocks.
This simplifies current workflow - filtering with ptdump and disassemblying with ptxed.
Additionaly:
* Depends on unpatched version of libipt
* Doesn't depend on ptxed
Example output:
```
{ "event": "drakvuf_event", "data": 1230 }
{ "event": "drakvuf_event", "data": 1231 }
{ "event": "drakvuf_event", "data": 1233 }
{ "event": "drakvuf_event", "data": 1234 }
{ "event": "drakvuf_event", "data": 1236 }
{ "event": "drakvuf_event", "data": 1237 }
{ "event": "drakvuf_event", "data": 1239 }
{ "event": "drakvuf_event", "data": 1240 }
{ "event": "drakvuf_cr3", "data": "0x187000" }
{ "event": "drakvuf_tid", "data": 0 }
{ "event": "drakvuf_cr3", "data": "0x947eb000" }
{ "event": "drakvuf_tid", "data": 1924 }
{ "event": "block_executed", "data": …
```
> drakcore: Add ipt-blocks

- drakrun/drakrun/vm.py
This patch prevents storage rollback when trying to spin up vm-0.
> drakrun/vm: Don't restore vm-0 storage

- drakcore/drakcore/util.py
This PR does a minor refactoring for using `urlsafe_b64encode` function directly
> drakcore: minor refactor(using secrets.token_urlsafe now)

- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
Testing for regressions in analysis should be an important part of the
development process. Currently, we have not way to determinte if we're
going in a good direction.
This patch adds a few knobs to enable testing samples.
New configuration variables
sample_testing - enables / disables test code paths
test_filters - overrides type of test tasks, default -
type:sample-test platform:win32/64
test_header - overrides output headers of test analyses, default -
type:analysis-test kind:drakrun
Apart from new filters and new headers, artifacts generated from test
tasks will be managed by karton and not stored indefinitely.
> drakrun: Add support for test analyses

- drakrun/drakrun/main.py
On Windows 10 there is a huge bloat of background processes which significantly delays the start of the target process. Injection succeeds but it waits till the new process is seen and it might go far behind the current 5 second time limit.
related #510
> drakrun: increase injection timeout to 60 seconds

- drakcore/drakcore/frontend/src/UploadSample.js
- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
* remove `enable_ipt` from `config.ini`, IPT is just enabled by requesting activation of `ipt` plugin
* activating `ipt` implies activation of `codemon`
* provide appropriate switches for `codemon`
> drakrun: fix IPT support

- drakrun/drakrun/drakpdb.py
- drakrun/requirements.txt
Both pdbparse 1.4 and 1.5 (latest release) have troubles parsing some of the PDBs:
* Windows/System32/ole32.dll
* Windows/SysWOW64/ole32.dll
* Windows/System32/urlmon.dll
* Windows/SysWOW64/urlmon.dll
The isssue seems to be resolved on the master branch. Add the specific
version to the requirements.txt and fix some of the issues that cause
the processing to fail on our side.
> drakpdb: Fix profile generation for a few PDBs

- examples/consumer.py
DirectoryResource was removed and the example crashes on import.
> examples: Remove unused imports from consumer.py

- .drone.yml
- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/drakpdb.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- test/conftest.py
> drakrun: Attach profiles to analyses

- drakcore/requirements.txt
1.2.1 has requirements that conflict with malduck 4.1.0
> drakcore: Bump msql to 1.2.2

- scripts/split_log.sh
Add a simple script that can be used for manual splitting of DRAKVUF
logs. Useful for development and testing.
> scripts: Add split_log.sh

- drakrun/drakrun/drakpdb.py
- drakrun/drakrun/draksetup.py
Moved the DLLPath in profile to a new section - $EXTRAS.
Added DLL ImageBase from DLL as requested by @catsuryuu.
> drakpdb: Add ImageBase to profiles

- drakrun/drakrun/drakpdb.py
Based on the comment `Don't use DRAKVUF arguments, they're used by wmimon which is compiled out`, we should comment out the `--json-combase` argument as it is part of the `WMIMON` plugin as well based on Drakvuf source code in `main.cpp` (https://github.com/tklengyel/drakvuf/blob/master/src/main.cpp#L249)
**WMIMON Plugin Arguments:**
```cpp
#ifdef ENABLE_PLUGIN_WMIMON
"\t --json-mpr <path to json>\n"
"\t                           The JSON profile for mpr.dll\n"
"\t --json-ole32 <path to json>\n"
"\t                           The JSON profile for ole32.dll\n"
"\t --json-wow-ole32 <path to json>\n"
"\t                           The JSON profile for SysWOW64/ole32.dll\n"
"\t --json-combase <path to json>\n"
"\t                           The JSON profile for combase.dll\n"
#endif
```
As it …
> Disable WMIMON/json-combase in Drakrun (Analysis Failures)

- drakcore/drakcore/process.py
- drakrun/drakrun/main.py
If analysis emits no logs while processing a task, uploading log file to
object store will fail - karton disallows empty resources.
Skip uploading when there's no data.
Generated stacktrace:
```
Traceback (most recent call last):
File "/opt/venvs/drakcore/lib/python3.7/site-packages/drakcore/process.py", line 56, in wrapper
res.upload(self.backend)
File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/resource.py", line 322, in upload
raise RuntimeError("Can't upload resource without content")
RuntimeError: Can't upload resource without content
```
> drakrun, drakcore: Check size of uploaded log file

- drakrun/drakrun/main.py
This is a small fix – currently when no plugins are selected from gui, the drakvuf will be spawned with all plugins enabled.
> Enable running drakvuf without plugins from gui

- drakrun/drakrun/draksetup.py
qcow2 snapshot method is a noop. If we keep the VM running after
performing a state snapshot, the image may become dirty and inconsistent
with the data cached in the OS.
Change this behavior to:
1. Stop vm-0 as soon as possible
2. Use VM restore mechanism to generate usermode profiles
> draksetup: Fix qcow2 handling

- drakcore/drakcore/frontend/src/AnalysisMain.js
- drakrun/drakrun/main.py
At some point, we might start relying on this information. For example on the frontend side, we might first download metadata and then display ProcessTree/BehavioralGraph based on whether the `procmon` was enabled during analysis instead of using `try catch` as `if` statements.
> Enrich metadata with list of plugins that were used during analysis

- drakcore/drakcore/frontend/src/AnalysisMain.js
- drakrun/drakrun/main.py
Analysis that was run without procmon plugin enabled will fail to load metadata – as it fails early in `componentDidMount`.
> Gui view fix

- .drone.yml
- drakrun/MANIFEST.in
- drakrun/drakrun/test/test_network.py
- test/conftest.py
- test/test_drakrun.py
* Change network ID in order to not collide with running drakrun service
* Run drakrun tests in E2E testing VM
This is not the sanest way to do this, but current CI setup is somewhat
limiting.
> include drakrun tests in CI

- drakrun/drakrun/main.py
Python `subprocess` doesn't like `int` path elements :(
> drakrun: fix bug with anti API hammering

- README.md
Freenode is dead. And most of the people are contacting us on Slack.
> readme: Remove Freenode channel info

- drakrun/drakrun/networking.py
Before configuring the output interface, add a sanity check if it's a valid name
> drakrun/net: Verify interface name

- drakcore/drakcore/postprocess/pstree.py
Tested. Should work fine with current drakvuf.
**Features**
1) should fix the issue with 2 processes with the same pid during a single analysis
2) logs arguments - the next step could be displaying them on the frontend
```json
{
"pid": 2004,
"procname": "\\Device\\HarddiskVolume2\\Users\\janusz\\Desktop\\malwar.exe",
"args": [],
"ts_from": 0,
"ts_to": 1625823132.913998,
"children": [
{
"pid": 2896,
"procname": "C:\\Users\\janusz\\AppData\\Local\\Temp\\AdvancedRun.exe",
"args": [
"\"C:\\Users\\janusz\\AppData\\Local\\Temp\\AdvancedRun.exe\"",
"/EXEFilename",
"\"C:\\Windows\\System32\\sc.exe\"",
"/WindowState",
"0",
"/CommandLine",
"\"stop WinDefend\"",
"/StartDirectory",
"\"\"",
"/RunAs",
"8",
"/Run"
],
"ts_from": 1625823125.635295,
"ts_to": 1625823127.423111,
"children": []
}
]
}
```
> Rewrite pstree

- drakcore/drakcore/postprocess/pstree.py
There is a small race when the process creates a child and terminates right after. This is due NtTerminateProcess not being accurate. In logs, it looks like the parent process has first terminated and only then spawned a child process.
**Requires drakvuf bump to [5291824](https://github.com/tklengyel/drakvuf/commit/52918240e7c6bf1c5f635978109809c26b8f549b)**
> Stop relying on NtTerminateProcess in pstree

- drakrun/drakrun/sample_startup.py
Small fix as `VBA_Parser` throws an exception when constructed from a file that cannot contain macro.
> Extract macros only from some office formats

- drakrun/drakrun/drakpdb.py
> Add missing `advapi32.dll` in `drakpdb.py`

- drakrun/drakrun/drakpdb.py
Installation with Windows 10 x64 leads to the following error during
postinstall:
```
[2021-09-20 14:36:20,042][DEBUG] Parsing PDB into JSON profile...
[2021-09-20 14:36:21,678][DEBUG] stdout: {"Plugin": "inject", "TimeStamp": "1632141365.020867", "Status": "Success", "ProcessName": "C:\\Windows\\System32\\win32k.sys", "Arguments": "", "InjectedPid": 0, "InjectedTid": 0}
[2021-09-20 14:36:21,679][DEBUG] stderr: DRAKVUF injector v0.8-git20210807130654+d74df17-1 Copyright (C) 2014-2021 Tamas K Lengyel
[2021-09-20 14:36:21,679][DEBUG] rc: 0
[2021-09-20 14:36:21,679][DEBUG] Traceback (most recent call last):
File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 579, in create_rekall_profile
profile = make_pdb_profile(
File …
```
> drakrun: Add missing T_64PCHAR pdbparse base_types

- drakrun/drakrun/main.py
When starting the VM the IP address is sometime the same as that of the vm-0. This blocks all internet connection.
Using ipconfig /release reassign correct address.
> drakrun: Add ipconfig release before renew

- drakcore/drakcore/systemd/drak-minio.service
Replace ionice call with direct usage of systemd service configuration
> drakcore/minio: Don't use ionice in service

- drakrun/drakrun/playground.py
Makes sure the virtual network adapters and bridges are set up _before_ dnsmasq is started, such that dnsmasq can bind to them.
Fixes #704
> First restore VM playground, then start dnsmasq.

- docs/drakpdb.rst
Since #620 the `pdb_guid` action has been renamed to `pe_codeview_data`, and its output has also changed slightly.
> Update documentation for the drakpdb tool

- drakcore/debian/rules
- drakrun/package/Dockerfile
- test/conftest.py
- test/vm-runner-client/vm_runner_client/client.py
Actually we should get rid of embedding minio and downloading drakvuf-bundle/xtf explicitly during packaging.
> CI: Temporarily set download links to CDNs (minio.drakvuf.cert.pl is no longer a thing)

- test/conftest.py
- test/test_sanity.py
- test/utils.py
Defining dependencies explicitly in test suite actually doesn't work because they're bound to specific version/distribution (`debian:buster`). If we want to build .deb for multiple versions, we need to rely on dependencies written in package.
> CI: Let .deb install any dependencies it wants

- drakrun/drakrun/sample_startup.py
Files detected as .vbe are often also runnable with wscript, for example 18b75005950d9e39a1eb5ce18453e23e00ddecb2ac941967686f8a27b2db9ef9.
> Use wscript to run files detected as vbe

- .github/workflows/build.yml
- ci/build_bundle.sh
- ci/build_utils.sh
- ci/custom_bundle.sh
- drakrun/drakrun/injector.py
- test/conftest.py
Drakvuf downgrade to last stable version that actually works on CERT.pl production setup.
After tests, drakvuf-sandbox has not been proven stable enough to work with Drakvuf v1.0, so we need to make a step back and then try once again. Changes before the downgrade are tracked on `drakvuf-v1.x` branch, so things applicable only to v1.0+ version can be still developed there.
**If you read this to roll it back to v1.0:**
- `.github/workflows/build.yml` changes should be OK for both versions, only SNAPSHOT_VERSION must be changed
- other changes can be simply reverted
> Drop drakvuf to v0.8-backports version

- .github/workflows/build.yml
> build.yml: use setup-node instead of curl | bash, node.js bump 14 -> 16

- drakrun/drakrun/config.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- drakrun/drakrun/playground.py
- drakrun/drakrun/test/test_util.py
- drakrun/drakrun/util.py
There's some significant code duplication here, so I think it may be useful to unify it.
Unfortunately it adds lines of code instead of removing them because of new imports, but it's actually less code.
> Change runtimeinfo parameter to path

- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/drakpush.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- drakrun/drakrun/regression.py
- drakrun/drakrun/util.py
- test/conftest.py
By default karton config is patched every time after loading with contents from "/etc/drakcore/minio.env". Remove this feature.
> Remove config patching

- drakrun/drakrun/main.py
Remove:
* Reconfiguration function (now if user wants to override identity or binds, they have to use regular karton cmdline flags
* Special handling of tests cases (we lose "volatility", but it should be implemented natively in karton anyway with a separate tag)
> Remove mandatory reconfiguration

- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- drakrun/drakrun/networking.py
- drakrun/drakrun/playground.py
- drakrun/drakrun/sample_startup.py
- drakrun/drakrun/storage.py
- drakrun/drakrun/util.py
- drakrun/drakrun/vba_graph.py
- drakrun/drakrun/vm.py
- Reaching root logger via `logging` module-level methods is highly discouraged because:
> This function (as well as [info()](https://docs.python.org/3/library/logging.html#logging.info), [warning()](https://docs.python.org/3/library/logging.html#logging.warning), [error()](https://docs.python.org/3/library/logging.html#logging.error) and [critical()](https://docs.python.org/3/library/logging.html#logging.critical)) will call [basicConfig()](https://docs.python.org/3/library/logging.html#logging.basicConfig) if the root logger doesn’t have any handler attached.
- Library/utils code should never use root loggers and drakrun module hierarchy should be used instead.
- "drakrun.*" logs can be easily redirected to Karton logger by attaching Karton handler to `drakrun` (which was already done)
> Log within correct logging hierarchy

- drakrun/drakrun/main.py
- drakrun/drakrun/py-scripts/drakpdb
- drakrun/drakrun/py-scripts/drakplayground
- drakrun/drakrun/py-scripts/drakpush
- drakrun/drakrun/py-scripts/drakrun
- drakrun/drakrun/py-scripts/draksetup
- drakrun/drakrun/py-scripts/draktest
- drakrun/drakrun/py-scripts/draktestd
- drakrun/setup.py
I guess it was more easy during development to run such script directly from the directory, but the recommended way are console_scripts. With a good package design, we can call a specific tool with `python3 -m` anyway.
> Use 'console_scripts' instead of 'scripts' in drakrun

- drakrun/drakrun/main.py
Make it a bit more logical, i.e.:
* move early returns even earlier
* factor some self-contained code into helpers like `filename_for_task`
> Reorder the startup procedure

- drakrun/drakrun/main.py
This function is a relic from a very old karton version, and not necessary now
> Remove safe get headers

- drakrun/drakrun/lib/sample_startup.py
- drakrun/drakrun/lib/vba_graph.py
- drakrun/drakrun/main.py
TODO for the nexts PR: completely eliminate the concept of the "workdir" and "outdir".
* workdir is unnecessary
* outdir should be a regular target directory (temporary directory for karton), cleaned after analysis
> Refactor startup command handling

- drakrun/drakrun/lib/sample_startup.py
- drakrun/drakrun/main.py
- drakrun/requirements.txt
Uses [mslex](https://github.com/smoofra/mslex) to provide proper quoting. I also tried to separate entrypoint and file type classification from actual command-line building.
I still don't like it though, because command provided by user is not processed as it should be (we should avoid placeholders like `%f`). I also don't understand why we try to include all macros explicitly and why first export is the best export in DLL.
> Proper startup command escaping

- .github/workflows/build.yml
- drakrun/setup.py
Python 3.6 is not supported and it blocks us from dependency upgrades (e.g. ipython #766, pydantic going to be introduced in #878 etc.)
I left `matrix` strategy in case we want to test it on newer Debian versions.
> Drop support for Debian Buster, set minimum requirement to Python 3.8

- drakrun/drakrun/drakpush.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/lib/config.py
- drakrun/drakrun/lib/install_info.py
- drakrun/drakrun/lib/paths.py
- drakrun/drakrun/lib/storage.py
- drakrun/drakrun/lib/vm.py
- drakrun/drakrun/main.py
- drakrun/drakrun/playground.py
- drakrun/drakrun/regression.py
- drakrun/drakrun/test/test_lvm.py
- drakrun/drakrun/test/test_vm.py
- drakrun/requirements.txt
- test/conftest.py
In current version we use Karton config while `drakrun.lib` should be independent from Karton. In addition: knowledge about default values and relationships between configuration fields is dispersed in drakrun modules, mainly in main.py
In this PR I try to map current configuration layout using Pydantic to provide single, coherent object that can be used in various drakrun components.
> Handle drakrun config in dedicated object (DrakrunConfig)

- drakrun/drakrun/test/test_network.py
As it's independent test that doesn't check anything related with `setup_vm_network`, we should use default chains.
> Fix flaky test: DRAKRUN_INP is not guaranteed to be set without network_setup_test

- drakrun/drakrun/analyzer.py
- drakrun/drakrun/main.py
- drakrun/setup.py
To make things less hardcoded in the Karton service itself, let's move analysis process to the separate module called "analyzer"
Analyzer is parametrized by `AnalysisOptions` object that is composed from configuration file values and task parameters. `analyzer.analyze_sample` and `AnalysisOptions` interface is used both by DrakrunKarton and new CLI tool called `drakstart` that allows to run raw analysis process directly from CLI. It will be useful tool for setup and further development and debugging.
List of things implemented a bit different than in the original code:
- Sample is downloaded to `/tmp/drakrun/vm-<N>/sample` instead of `/tmp/drakrun/vm-<N>/<target_name>`. The target file name (which is usually `malwar.exe`) is used only when writing file to the target VM.
- `metadata.json` …
> Separate 'analyzer' module

- drakrun/drakrun/data/config.ini
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/lib/config.py
- drakrun/drakrun/lib/minio.py
- drakrun/drakrun/main.py
- drakrun/drakrun/web/app.py
- drakrun/requirements.txt
- drakrun/setup.py
- Karton was updated to v5. Karton 5 uses boto3 as S3 binding so we need to make our own `minio.Minio` object when we want to make direct calls to the MinIO instance
- In previous version: logs were collected in memory and then flushed to the file and Karton resource. I changed the behavior to write logs directly to the file using `FileHandler` set on root logger (as we want to collect logs from other components as well)
> Upgrade Karton to v5 and change log handling

- drakrun/drakrun/main.py
Don't clobber output dir, write drakmon.log to root analysis dir, because analyzer expects that output dir is empty
> Fix: drakrun.log handling

- drakrun/drakrun/ipt_disasm.py
fix: FileNotFoundError: [Errno 2] No such file or directory: \'ipt/dumps/(null)\'
> Fix opening the file error in drakrun/drakrun/ipt_disasm.py when codemon failed to save the dump.

- drakrun/drakrun/analyzer.py
Right now, Drakvuf isn't really good at handling Unicode names, leaving them in native encoding and placing directly into JSON string
```
JSON decode error occurred when tried to parse injector's logs. Raw log line: b'{"Plugin": "inject", "TimeStamp": "1720614534.086632", "Method": "WriteFile", "Status": "Success", "ProcessName": "C:\\\\Users\\\\user\\\\Desktop\\\\FV-xxx dasdasd Zapytanie o cen\\304\\231 arbejdsmetodes.bat", "Arguments": "dasdasd Zapytanie o cen\\304\\231 arbejdsmetodes.bat", "InjectedPid": 0, "InjectedTid": 0}\n'
```
As a workaround, this PR converts'/removes Unicode characters into ASCII. If we're left with empty name, random name will be generated.
> Normalize/remove Unicode characters in file names

- drakrun/drakrun/analyzer.py
Currently filenames are not really filtered, because filtered version is overwritten in the if branch.
> Fix filename filter

- drakrun/drakrun/analyzer.py
If `sample_filename` is not provided, use sample_path.name instead. With this change we can make sample_filename required (non-Optional) in AnalysisOptions. The rest of the code assumes this already.
> Make sample_filename required

- drakrun/drakrun/draksetup/mount.py
- drakrun/drakrun/lib/bindings/xen.py
- drakrun/drakrun/playground.py
```
Traceback (most recent call last):
File "/opt/venv/bin/drakplayground", line 5, in <module>
from drakrun.playground import main
File "/opt/venv/lib/python3.9/site-packages/drakrun/playground.py", line 12, in <module>
from drakrun.draksetup import insert_cd
ImportError: cannot import name 'insert_cd' from 'drakrun.draksetup' (/opt/venv/lib/python3.9/site-packages/drakrun/draksetup/__init__.py)
```
Bug introduced in https://github.com/CERT-Polska/drakvuf-sandbox/pull/925
> Fix: drakplayground missing import after refactoring

- drakrun/drakrun/draksetup/util/profile_builder.py
- drakrun/drakrun/lib/drakpdb.py
Some of them are actually "required" by plugins.
> Fix: not all 'unrequired' profiles are apivectors profiles

- drakrun/drakrun/lib/injector.py
- drakrun/drakrun/lib/util.py
Related with https://github.com/CERT-Polska/drakvuf-sandbox/issues/933. Injector supports `-I` option that allows to pin injector to the specific TID.
> Basic support for injector TID pinning

- drakrun/drakrun/lib/postprocessing/build_process_tree.py
As said in https://github.com/CERT-Polska/drakvuf-sandbox/issues/679 and https://github.com/CERT-Polska/drakvuf-sandbox/issues/938 - PPIDs are not guaranteed to be real and can be reused. On the other hand, initial enumeration of processes is done in order of EPROCESS linked list, so new processes should be further in list than older ones.
It means that if we have situation like:
```
{"PID": 348, "PPID": 336, "name": "csrss.exe"}
...
{"PID": 336, "PPID": 1984, "name": "taskhost.exe"}
{"PID": 2044, "PPID": 336, "name": "some_child_of_taskhost.exe"}
```
taskhost is further on list, so PPID of csrss.exe is phantom (and should be treated as process without parent) and the real children of PPID 336 are placed further in list.
In this PR:
- I removed creation of Mocked processes as creating a …
> Fix MultipleProcessesReturned caused by parent PID reuse

- .github/workflows/build.yml
- docs/usage/getting_started.rst
- drakrun/.gitignore
- drakrun/Makefile
Until this moment I was a bit lazy and was fetching the .whl package from CI artifacts for manual testing. That's why in this PR I have:
- added `Makefile` to build and install Drakvuf Sandbox package from sources 
- modified CI to use make to actually build the whole .whl package
- added proper documentation
> CI: Add Makefile for building complete wheel

- .github/workflows/build.yml
- .gitmodules
- drakrun/Makefile
- drakrun/drakrun/tools/Makefile
Makefile doesn't build `test-hvm64-example` XTF tool, it's build only in CI workflow.
This PR adds proper submodule and proper Makefile instructions.
> CI: Consistent linking with XTF

- drakrun/.flake8
- drakrun/pyproject.toml
Right now linters try to lint code of external dependencies. We need exclusions for directories containing submodules.
> Fix: don't lint tools and data

- drakrun/drakrun/draksetup/init.py
- drakrun/drakrun/draksetup/util/ensure_dirs.py
- drakrun/drakrun/lib/paths.py
`draksetup init` doesn't create all directories, including `/var/lib/drakrun`. This PR fixes this problem.
> Fix: missing dirs creation by 'draksetup init'

- drakrun/drakrun/analyzer.py
- drakrun/drakrun/data/vm-post-restore.ps1
- drakrun/drakrun/draksetup/init.py
> Configurable post-restore script and time synchronization

- drakrun/drakrun/draksetup/postinstall.py
- drakrun/drakrun/draksetup/scale.py
- `draksetup scale 0` would be very useful command to stop drakrun services. This PR allows to set 0 as number of instances
- `draksetup postinstall` enables new drakrun instance automatically which is sometimes pretty annoying and unexpected. It's more clear to let user enable new worker manually by typing "draksetup scale 1"
> Allow 0 in draksetup scale to disable services, don't enable first drakrun worker on draksetup postinstall

- drakrun/drakrun/lib/install_info.py
- drakrun/drakrun/lib/paths.py
- drakrun/drakrun/lib/storage.py
- drakrun/requirements.txt
StorageBackend objects should have single source of configuration (InstallInfo), right now it's a bit scattered over the file.
This PR also adds:
- new fields in InstallInfo that should contain everything that is mapped to xl.cfg.template.
- InstallInfo uses Pydantic instead of dataclasses_json
- removed unnecessary shell calls
- lvm_snapshot_size isn't just a magic hardcoded number but a configurable field
- removed `enable_unattended`, `iso_path` and `iso_sha256` fields. It's not a VM state and we don't care about it further.
This is an isolated patch from my internal rework of drakrun and may be incompatible with other parts of code right now. I just want to have reasonable diffs in commits.
> InstallInfo and StorageBackend reworked

- drakrun/drakrun/lib/network_info.py
- drakrun/drakrun/lib/networking.py
- drakrun/drakrun/lib/paths.py
- Current state of network is kept in `/var/run/drakrun/vmnet-N.json` files, so we can target the exact iptables rules and other things instead of looking for them with regexes and guessing.
- dnsmasq is always run in the background and signalled via its PID file
- DHCP is limited to `10.13.{vm_id}.2` address for the VM so we don't have that .100-200 randomness. I think it would make further debugging a bit easier.
- Interface is more ready to customize the network pool in the future
Right now it's a bit detached from the configuration file.
> Refactor of networking

- drakrun/MANIFEST.in
- drakrun/Makefile
- drakrun/drakrun/draksetup/drakshell.py
- drakrun/drakrun/draksetup/main.py
- drakrun/drakrun/lib/drakshell.py
- drakrun/drakrun/tools/Makefile
- drakrun/drakrun/tools/drakshell/.gitignore
- drakrun/drakrun/tools/drakshell/Makefile
- drakrun/drakrun/tools/drakshell/drakshell.c
- drakrun/drakrun/tools/drakshell/include/nt_loader.h
- drakrun/drakrun/tools/drakshell/linker.ld
- drakrun/drakrun/tools/drakshell/nt_loader.c
- drakrun/drakrun/tools/drakshell/thread_start.S
Reintroduced the idea from https://github.com/CERT-Polska/drakvuf-sandbox/pull/945
It assists the injector by providing a well-known looping thread inside explorer.exe that would be a good target for hijacking and injection. The thread will be periodically woke up due to short timeout on blocking operations and will report its TID over the communication channel with the host, so it can be identified.
Another nice feature is that it allows to execute provisioning commands interactively. I have added `draksetup drakshell` command that allows to run a cmd.exe/powershell.exe command (actually any basic console tool would work)
> drakshell v2: bootstrap agent to assist injector in VM provisioning phase

- drakrun/drakrun/draksetup/main.py
- drakrun/drakrun/draksetup/make_profile.py
Adds "make-profile" command that allows to refresh profile based on vm-1 state in case we need only small changes.
This is rarely used but useful command during debugging and development.
> draksetup: add 'make-profile' and reorder commands

- drakrun/drakrun/analyzer.py
- drakrun/drakrun/lib/networking.py
Isolated from #1007.
On my testbed I don't have the Emulated interface because I use PV drivers for networking. We should not even bother about Xen virtual interfaces because we're already providing a bridge that is unique for each VM.
> Fix: tcpdump on drakN bridge instead of vifX.0-emu interface

- drakrun/drakrun/draksetup/drakshell.py
- drakrun/drakrun/lib/drakshell.py
Isolated from #1007 
- added SIGINT handling into DrakshellInteractiveProcess.join
- extended timeouts within drakshell in case VM is sluggy just after the restore
> drakshell: longer timeouts, move SIGINT handler to join method

- drakrun/analyzer/analyzer.py
- drakrun/analyzer/run_tools.py
- drakrun/lib/drakvuf_cmdline.py
- drakrun/tools/drakshell/drakshell.c
- drakrun/tools/drakshell/include/nt_loader.h
- drakrun/tools/drakshell/nt_loader.c
When sample and Drakvuf are executed asynchronously, it may cause weird effects like https://github.com/CERT-Polska/drakvuf-sandbox/issues/1042. We're also limiting ourselves to execution via drakshell while drakshell should be an opt-out addition.
I this PR I included the following changes:
- wrapped drakshell main loop in extra thread (drakshell_loop) which is tracked by drakshell_main. If drakshell_loop exits by external or internal termination, drakshell_main does the necessary cleanup.
- sample is executed using injector with  "--exit-injection-thread" flag when `inject_tid` is set. This is meant to terminate drakshell_loop and evacuate the drakshell from the explorer.exe memory before the sample is fully loaded.
- bugfix: `options.start_command` is used as a command-line instead of …
> Run sample using injector and evacuate drakshell on injection

- drakrun/analyzer/postprocessing/plugins/__init__.py
- drakrun/analyzer/postprocessing/plugins/generate_report.py
This PR adds a post processing plugin for generating JSON analysis reports. The format of the JSON report is the one agreed upon previously with the mentor (see attached example: [report.json](https://github.com/user-attachments/files/16385616/report.json))
This PR should be merged after the TTPs PR (https://github.com/CERT-Polska/drakvuf-sandbox/pull/919) gets merged first.
Note: This PR is the same as #927 . I have closed the other one since rebasing it to master after all the changes was more complicated than creating a new PR.
> Generate DRAKVUF analysis report

- .flake8
- .github/workflows/build.yml
- drakrun/analyzer/analyzer.py
- drakrun/analyzer/postprocessing/plugins/plugin_base.py
- drakrun/analyzer/worker.py
- drakrun/web/app.py
- pyproject.toml
- setup.py
3.8 is EOL and it's difficult to bump dependencies. Recommended Debian 12 comes with Python 3.11.
> Bump minimal Python version to 3.9, fix linter configuration

- drakrun/analyzer/analysis_options.py
- drakrun/analyzer/analyzer.py
- drakrun/analyzer/postprocessing/plugins/__init__.py
- drakrun/analyzer/postprocessing/plugins/screenshot_metadata.py
- drakrun/analyzer/run_tools.py
- drakrun/analyzer/screenshotter.py
- drakrun/cli/analyze.py
- requirements.txt
- Analyzer connects to VNC and makes periodic screenshots. If screenshot perceptual hash significantly differs, screenshot is stored in `screenshots` subdir of analysis directory
- `screenshots.json` aggregates information about timestamp, hashes and screenshot index
closes https://github.com/CERT-Polska/drakvuf-sandbox/issues/608
> analyzer: Make automatic screenshots during analysis

- requirements.txt
Fix for `ModuleNotFoundError: No module named 'cv2'` message after fresh installation
> Fix: missing Perception peer dependency

- drakrun/web/api.py
- drakrun/web/schema.py
flask-openapi3 tries to parse JSONs from form fields automatically, so we should just expect a list of plugins in the scheme
> Fix: don't parse plugins explicitly in upload endpoint

- docs/conf.py
- drakrun/version.py
- drakrun/web/frontend/package-lock.json
- drakrun/web/frontend/package.json
- drakrun/web/frontend/src/App.jsx
New changes:
* Automatic screenshots during analysis process (https://github.com/CERT-Polska/drakvuf-sandbox/pull/1052, https://github.com/CERT-Polska/drakvuf-sandbox/pull/1063)
* drakweb: Moved API endpoints under /api prefix. API is now documented and using flask-openapi3 for generating OpenAPI specification and validation (https://github.com/CERT-Polska/drakvuf-sandbox/pull/1068)
* drakweb: Filtered process logs viewer (https://github.com/CERT-Polska/drakvuf-sandbox/pull/1064)
* Sample is run using injector and drakshell is evacuated on injection. It's recommended to run this version with latest DRAKVUF to include [this patch](https://github.com/tklengyel/drakvuf/commit/9833fa5ffd821b11aa78ef8a7a455da623580b55) (https://github.com/CERT-Polska/drakvuf-sandbox/pull/1047)
* Minimal Python …
> Bump version: v0.19.0-alpha3

- drakrun/analyzer/postprocessing/indexer.py
- drakrun/analyzer/postprocessing/plugins/__init__.py
- drakrun/analyzer/postprocessing/plugins/index_logs.py
- drakrun/web/analysis.py
- drakrun/web/api.py
- requirements.txt
- Make a single `log_index` file for logs instead of hundreds of `index/{name}.{seqid}.json` files
- Use msgpack to make it more compact
> Compact log index

- drakrun/analyzer/analyzer.py
- drakrun/analyzer/run_tools.py
This change should allow to use relative paths in AnalysisOptions.extra_drakvuf_args.
> Fix: change Drakvuf working dir to analysis output dir

- drakrun/tools/drakshell/nt_loader.c
PEB_LDR_DATA definition is wrong. I don't know why it was working...
> Update nt_loader.c: fix PEB_LDR_DATA

- drakrun/analyzer/analyzer.py
- drakrun/web/frontend/src/AnalysisMetadataTable.jsx
- drakrun/web/frontend/src/ProcessInfoTable.jsx
User can actually provide command line using both types. The list is then stringified using mslex, but originally appears in metadata just like provided by user.
> Fix: issues when start_command is provided as str instead of list

- drakrun/lib/vmi_profile.py
After changing logging configuration, we don't see any useful log during VMI profile generation (only progress bars). This PR adds additional logging to the extract_dll_profile function.
> Fix: missing log for extract_dll_profile
