CERT-Polska/drakvuf-sandbox

- README.md
> Enhance troubleshooting section in README.md

- drakcore/debian/rules
> Fix that frontend build is being ran twice

- README.md
> Add build status badge 

- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
> Warn about blank minio access_key

- .drone.yml
- drakcore/debian/rules
> Use cached minio server for drakcore

- drakrun/drakrun/draksetup.py
- drakrun/drakrun/run.py
Allow to use `zfs` as a storage backend, alternatively to the default `qcow2`.
resolve #20
> Implement ZFS support

- README.md
- drakcore/debian/control
- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/package-lock.json
- drakcore/drakcore/frontend/package.json
- drakcore/drakcore/frontend/src/AnalysisList.js
- drakrun/drakrun/main.py
- drakrun/requirements.txt
- test/conftest.py
* Add the output equivalent to `file` command in the analysis list (web UI), near each sample (resolve #18)
* Bump npm dependencies
> Add output from python-magic to the analysis list

- README.md
- drakcore/package/Dockerfile
- drakcore/package/build.sh
- drakrun/package/Dockerfile
- drakrun/package/build.sh
* Change build base to Ubuntu 18.04
* Make small adjustments so it works on both bases (Debian Buster/Ubuntu 18.04)
> Make package build also compatible with Ubuntu 18.04

- drakcore/drakcore/app.py
- drakcore/drakcore/pstree.py
- drakcore/tests/test_process_tree.py
> Generate process tree from procmon logs

- README.md
> Add instructions about ZFS installation

- CONTRIBUTING.md
> Create basic local development guidelines

- CONTRIBUTING.md
> Add information about debs.icedev.pl

- README.md
- drakcore/drakcore/config.dist.ini
- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
* ~~add some e2e test which involves network~~ (in the future)
* configurable outbound DNS (default: `8.8.8.8`)
* `net_enable` switch
* minimal adjustments in docs
* docs about optional usage of dnschef
> Enhance networking support

- drakcore/drakcore/frontend/src/AnalysisMain.js
- drakcore/drakcore/frontend/src/api/index.js
It's not very beautiful but it does the job.
Closes #12 
Preview:
> Display process tree in web UI

- drakcore/drakcore/frontend/src/AnalysisMain.js
- drakcore/drakcore/frontend/src/App.js
* `Move page content and footer inside wrapper` - fixes layout when displayed on smaller screen
* `Add vertical space between analysis cards` - adds some vertical space in analysis view
> Misc UI fixes

- drakcore/drakcore/frontend/src/AnalysisList.js
- drakcore/drakcore/frontend/src/AnalysisMain.js
- drakcore/drakcore/frontend/src/AnalysisStatus.js
- drakcore/drakcore/frontend/src/App.css
- drakcore/drakcore/frontend/src/App.js
- drakcore/drakcore/frontend/src/UploadSample.js
- drakcore/drakcore/frontend/src/api/index.js
- drakcore/drakcore/frontend/src/index.js
Default configuration formatting to normalize our codebase
> Reformat UI with Prettier

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/UploadSample.js
- drakcore/drakcore/frontend/src/api/index.js
- examples/push_sample.py
- test/utils.py
> Upload files via API

- examples/README.md
- examples/requirements.txt
* Add note about `examples/push_sample.py` script
* Explicitly list requests in `examples/requirements.txt`
> Update README for examples

- drakcore/debian/control
- drakcore/debian/rules
- drakcore/package/Dockerfile
- drakrun/debian/control
- drakrun/package/Dockerfile
> Ubuntu 20.04 compatibility - adjust package build process

- README.md
- drakcore/debian/drakcore.links
- drakcore/drakcore/bin/drak-healthcheck
- drakcore/requirements.txt
- drakcore/setup.py
> Add drak-healthcheck

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/AnalysisApicall.js
- drakcore/drakcore/frontend/src/AnalysisMain.js
- drakcore/drakcore/frontend/src/App.css
- drakcore/drakcore/frontend/src/App.js
- drakcore/drakcore/frontend/src/api/index.js
- drakcore/drakcore/postprocess/apicall.py
- drakcore/drakcore/postprocess/pstree.py
- drakcore/drakcore/process.py
> Display apimon logs in web UI

- drakcore/drakcore/frontend/src/AnalysisMain.js
> Show process tree when graph is generated

- drakcore/drakcore/frontend/src/AnalysisMain.js
> Enable ProcDOT graph zooming and fix error messages

- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
> Add optional syscalls filter

- README.md
- USAGE_STATISTICS.md
- drakcore/debian/changelog
- drakcore/drakcore/frontend/package-lock.json
- drakcore/setup.py
- drakrun/debian/changelog
- drakrun/drakrun/draksetup.py
- drakrun/setup.py
> Implement usage statistics and bump to 0.4.0

- .drone.yml
- drakcore/debian/rules
- drakcore/package/Dockerfile
- drakcore/package/build.sh
- drakcore/package/control.template
- drakcore/package/find-python.sh
- drakrun/debian/rules
- drakrun/package/Dockerfile
- drakrun/package/build.sh
- drakrun/package/control.template
- drakrun/package/find-python.sh
resolve #64
resolve #102
resolve #100
> dh-virtualenv: pin to specific Python version instead of using the default one

- .gitmodules
- drakrun/drakrun/draksetup.py
> Update DRAKVUF, add submodule

- drakcore/drakcore/postprocess/apicall.py
- drakcore/drakcore/postprocess/pstree.py
- drakcore/drakcore/process.py
- drakcore/drakcore/system.py
- drakcore/requirements.txt
- drakrun/drakrun/main.py
- drakrun/requirements.txt
- examples/requirements.txt
- test/conftest.py
- test/test_sanity.py
> Migrate to karton 3.1.0

- drakcore/drakcore/system.py
- test/conftest.py
- test/test_sanity.py
> Copy service logs to CI logs when error occurs

- .github/workflows/debs.yml
> Draft GitHub Release when new tag is pushed

- drakcore/debian/changelog
- drakcore/drakcore/frontend/package-lock.json
- drakcore/drakcore/frontend/package.json
- drakcore/setup.py
- drakrun/debian/changelog
- drakrun/setup.py
Just to test automated releases.
> Bump version to 0.5.1

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/UploadSample.js
- drakcore/drakcore/frontend/src/api/index.js
- drakrun/drakrun/main.py
- test/conftest.py
- test/test_sanity.py
- test/utils.py
closes #30 
Changed E2E test timeout from 10 minutes to 2 minutes to make CI faster ;)
> Add configurable analysis timeouts

- drakcore/drakcore/frontend/src/AnalysisApicall.js
> Add loading information to API call page

- drakrun/drakrun/main.py
> Add beter check for recognizing DLLs

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/UploadSample.js
- drakcore/drakcore/frontend/src/api/index.js
- drakrun/drakrun/main.py
> Rework upload component, add configurable start command and file name

- drakcore/drakcore/app.py
> fix error in /list endpoint

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/AnalysisMain.js
> drakcore: Add "Download dumps" button

- drakcore/drakcore/frontend/src/AnalysisMain.js
Add clickable tree collapsing and automatic detection of which subtree to expand by default
closes #123
> Collapse subtrees unrelated to malware process

- README.md
- drakrun/drakrun/drakpdb.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- drakrun/package/control.template
- test/conftest.py
closes #38. Also fixes smol missuses of `os.path.join`.
> Generate DLL profiles

- drakrun/package/Dockerfile
* Remove swab.patch hack from DRAKVUF package build process (fix Debian Buster build)
* Downgrade virtualenv version (fix Ubuntu Focal build)
> Fix package build process

- drakrun/drakrun/config.py
- drakrun/drakrun/drakpush.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- drakrun/drakrun/py-scripts/drakrun
- drakrun/drakrun/py-scripts/draksetup
- drakrun/drakrun/run.py
- drakrun/requirements.txt
* `ETC_DIR` / `LIB_DIR` can be overridden by `DRAKRUN_*` env variables
* Removed `ETC_DIR` / `LIB_DIR` variable injection between modules
* Move `install.json` handling to single place
> Configuration rework

- drakrun/drakrun/draksetup.py
- drakrun/drakrun/run.py
- drakrun/drakrun/storage.py
Extract logic used for handling ZFS/QCOW2 setups into uniform interface
> Add storage backends

- drakcore/drakcore/frontend/src/AnalysisMain.js
> add soft fail to graphviz component

- drakrun/drakrun/main.py
> Change dump ZIP directory structure

- drakcore/drakcore/postprocess/apicall.py
- drakrun/drakrun/main.py
- drakrun/drakrun/run.py
- test/conftest.py
- test/test_sanity.py
> Use injector instead of CD-ROM

- test/conftest.py
Bump DRAKVUF submodule to include patches for injector
> Bump DRAKVUF

- drakcore/drakcore/frontend/src/AnalysisApicall.js
- drakcore/drakcore/frontend/src/OptionPicker.js
Change component name and API into more generic version suitable
for using in multiple contexts.
> drakcore: frontend: Refactor ProcessFilter into OptionPicker

- drakcore/drakcore/frontend/src/AnalysisMain.js
- Whole DOT fetching and rendering is separated out to the AnalysisBehavioralGraph component
- Wrapped `<Graphviz>` with some memoization to re-render only if dot contents changed
- Added hotfix for unhandled exception `syntax error in line ... near '%'`. Procdot somehow produces `color = %s` attributes that Graphviz can't parse.
Closes #181
> Added AnalysisBehavioralGraph and fixed long-lasting graph rendering

- drakrun/drakrun/draksetup.py
should fix #240
**PLEASE TEST BEFORE APPROVING/MERGE** as it was not tested yet.
> Hotfix misconfigured click

- drakrun/drakrun/main.py
> Properly handle Unicode errors in drakmon.log parsing

- examples/consumer.py
> Fix bug in consumer.py

- examples/consumer.py
Tested, and working.
closes #248
> Fix consumer.py to use correct new API

- docs/index.rst
- docs/usage/upgrading.rst
> docs: Add info about upgrading

- README.md
* Add @kscieslinski 
* Add GitHub nickname and profile link for each maintainer
> Update the list of project maintainers

- .drone.yml
Split drakrun/drakcore packaging steps.
> ci: Small cleanups

- drakcore/drakcore/config.dist.ini
- drakcore/drakcore/system.py
> drakcore: add system_disable config switch

- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
- test/conftest.py
> drakrun: add configurable karton instance name

- drakrun/drakrun/drakparse.py
> drakrun: fix log handling errors in drakparse

- drakrun/drakrun/run.py
This should be already handled by storage backend code.
> remove obsolete qcow2 snapshot removal

- drakcore/drakcore/postprocess/pstree.py
- drakrun/drakrun/drakparse.py
requires DRAKVUF bump to at least https://github.com/tklengyel/drakvuf/commit/dbc57e1353e158048166bfb0ca4603bc48ad5327
also, worth waiting till this is merged https://github.com/tklengyel/drakvuf/pull/1049 (done)
DRAKVUF bump will resolve #270
> fix DRAKVUF log parsing

- examples/push_sample.py
> Fix errors in examples/push_sample

- README.md
* Make supported hardware/software information more readable by using emojis 😷
* List Windows 10 2004 as officially supported
> Update supported hardware&software in README

- drakrun/drakrun/storage.py
> drakrun: wait for NDB device to appear

- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- drakrun/drakrun/networking.py
- drakrun/drakrun/util.py
> drakrun: support network in installation process

- drakrun/drakrun/office.py
> Fix duplicate macro name bug in Office support

- drakrun/drakrun/main.py
> drakrun: don't use cmd.exe wrapper when executing target process

- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- drakrun/drakrun/test/test_util.py
- drakrun/drakrun/util.py
* Move vmi-win-offsets and get-explorer-pid calls into separate functions.
* Create dataclasses for handling runtime information
> drakrun: Refactor tool usage

- drakrun/drakrun/config.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/main.py
- drakrun/drakrun/storage.py
Add new constants:
- VM_CONFIG_DIR - VM config storage
- PROFILE_DIR - rekall profile storage
- VOLUME_DIR - iso/snapshots storage
and introduce them throughout drakrun code.
> drakrun: Add new directory constants

- drakrun/drakrun/injector.py
- drakrun/drakrun/main.py
Move injector handling into separate class to reduce code duplication and simplify further usage (for example if we switch from mounting the volume to using readfile mode)
> drakrun: Add Injector class

- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
> drakrun: Karton configuration overrides

- docs/usage/scaling.rst
- docs/usage/troubleshooting.rst
- drakcore/debian/postinst
- drakcore/debian/prerm
- drakcore/drakcore/bin/drak-healthcheck
- drakcore/drakcore/systemd/drak-postprocess@.service
- test/conftest.py
> make postprocessing more flexible

- ci/build_bundle.sh
- ci/build_utils.sh
Additionally:
+ Use Release VMI build
+ Enable VMI debugging with env variable
> ci: Refactor build functions

- ci/build_utils.sh
- ci/custom_bundle.sh
* Don't silence Xen building
* Use archive cp copy
* Fix path
> ci: Building fixes

- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
List of plugins in `config.ini` that are activated globally or depending on task's quality.
> Configurable active plugins (per task quality)

- drakrun/drakrun/draksetup.py
> Eject CD-ROMs before postinstall

- docs/index.rst
- docs/usage/getting_started.rst
- docs/usage/managing_snapshots.rst
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/storage.py
~~TODO: Spawn a VM after importing minimal snapshot (to do postinstall)~~
> draksetup: Add snapshot export/import

- drakcore/debian/drakcore.links
- drakcore/drakcore/bin/drak-gen-ptxed
- drakcore/drakcore/bin/drak-ipt-filter
- drakcore/drakcore/postprocess/__init__.py
- drakcore/drakcore/postprocess/ipt_disasm.py
- drakcore/setup.py
> drakcore: add tools drak-gen-ptxed and drak-ipt-filter

- drakrun/drakrun/main.py
> drakrun: fix typo in drakvuf invocation

- drakcore/drakcore/app.py
- drakcore/drakcore/config.dist.ini
- drakcore/drakcore/postprocess/apicall.py
- drakcore/drakcore/postprocess/cache_update.py
- drakcore/drakcore/postprocess/generate_graphs.py
- drakcore/drakcore/postprocess/ipt_disasm.py
- drakcore/drakcore/postprocess/log_index.py
- drakcore/drakcore/postprocess/pstree.py
- drakcore/drakcore/postprocess/slice_logs.py
- drakcore/drakcore/postprocess/wireshark_key_file_gen.py
- drakcore/drakcore/process.py
- drakcore/drakcore/system.py
- drakcore/drakcore/util.py
- drakcore/requirements.txt
- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/drakpush.py
- drakrun/drakrun/main.py
- drakrun/drakrun/util.py
- drakrun/requirements.txt
- examples/README.md
- examples/consumer.py
- examples/requirements.txt
- test/conftest.py
closes #396 
no changes in behavior
> Upgrade to karton4

- drakrun/drakrun/main.py
Analysis would crash if there was no value in config file
> drakrun: add fallback for use_root_uid

- drakcore/requirements.txt
- drakrun/requirements.txt
Also, pin version in drakrun requirements.
> Bump redis version

- drakrun/drakrun/networking.py
- drakrun/drakrun/vmconf.py
Using default logging triggers `basicConfig` and duplicate log printing on stderr
> drakrun/net: Use drakrun logger

- drakrun/drakrun/draksetup.py
During it at the top level is annoying when you import a function from draksetup module
> drakrun/setup: Move basicConfig to main function

- drakcore/requirements.txt
- drakrun/requirements.txt
It should resolve the issue with warning from requests
> Bump requests to 2.25.1

- drakrun/drakrun/main.py
Seems like no one is using it interally
> drakrun: Remove sample_sha256.txt

- drakrun/drakrun/util.py
Remove unused imports and sort them.
Add static method decorator to VmiOffsets class.
> drakrun/util: Minor cleanup

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/package-lock.json
- drakcore/drakcore/frontend/package.json
- drakcore/drakcore/frontend/src/App.css
- drakcore/drakcore/frontend/src/UploadSample.js
- drakcore/drakcore/frontend/src/api/index.js
- drakrun/drakrun/main.py
> Let user select plugins from web interface

- README.md
While reading the docs , just found a little grammatical typo
> Fix typo in the docs

- .drone.yml
- docs/usage/getting_started.rst
- drakrun/debian/rules
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/tools/Makefile
- drakrun/drakrun/tools/test-altp2m.c
- drakrun/drakrun/tools/test-hvm64-example.cfg
- drakrun/package/Dockerfile
Run simple diagnostics with XTF to ensure Xen&HVM&altp2m work OK.
> drakrun: add preflight check with XTF

- drakrun/drakrun/config.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/storage.py
- drakrun/drakrun/test/test_snapshot_time.py
> draksetup: LVM backend support

- drakrun/drakrun/draksetup.py
> draksetup: add sanity check for xl list

- drakrun/drakrun/playground.py
> playground: Fix cleanup call

- drakrun/drakrun/draksetup.py
- drakrun/drakrun/injector.py
- drakrun/drakrun/storage.py
fix #472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cert-polska/drakvuf-sandbox/486)
> drakrun: usermode profile generation using Injector

- drakrun/drakrun/main.py
Call `matches_filter` correctly
> drakrun: Fix test mode

- docs/index.rst
- docs/regression_testing.rst
- drakrun/debian/drakrun.links
- drakrun/drakrun/config.dist.ini
- drakrun/drakrun/main.py
- drakrun/drakrun/py-scripts/draktest
- drakrun/drakrun/py-scripts/draktestd
- drakrun/drakrun/regression.py
- drakrun/requirements.txt
- drakrun/setup.py
Example test set:
```
[
{
"sha256": "35e756ef1b3d542deaf59f093bc4abe5282a1294f7144b32b61f4f60c147cabb",
"extension": "dll",
"ripped": "emotet"
},
{
"sha256": "4239335443cbf3d45db485d33c13346c67d5ac717a57856315a166c190dde075",
"extension": "exe",
"ripped": "raccoon"
}
]
```
> drakrun: Dump regression tester

- docs/regression_testing.rst
- drakrun/requirements.txt
- adds the missing `mwdblib` in `requirements.txt`
- Includes docs about enabling `sample_testing` for performing regression tests
> drakrun: regression docs improvement

- drakrun/drakrun/main.py
> drakrun: handle errors in main loop more verbosely

- test/test_sanity.py
This should fix some CI failures
> e2e: Depend on drakcore being up when contacting  drak-web

- drakcore/drakcore/postprocess/generate_graphs.py
> Fix postprocess graph generation issue

- scripts/bump_version.json
- scripts/bump_version.py
Courtesy of @psrok1
"Borrowed" from  https://github.com/CERT-Polska/mwdb-core/pull/357
> scripts: Add bump_version.py

- drakcore/drakcore/frontend/src/App.js
And also fix copyright/reserved sings
> drakcore/frontend: Update footer dates

- README.md
> add join slack badge

- docs/usage/managing_snapshots.rst
- docs/usage/optional_features.rst
- drakrun/drakrun/playground.py
I could not find builtin way to set local help command.
> add mount and help commands to drakplayground

- drakcore/drakcore/process.py
- drakrun/drakrun/main.py
Looks like I got trolled by SO; `.len` was removed in Python3 :trollface:
> Repair invalid fix for Resource size check

- drakrun/drakrun/main.py
> drakrun: warning for falling back to exe

- drakrun/drakrun/drakpdb.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/util.py
> drakrun: seperate compulsory DLLs

- drakcore/drakcore/app.py
- drakcore/drakcore/frontend/src/UploadSample.js
- drakrun/drakrun/main.py
- drakrun/drakrun/sample_startup.py
- drakrun/drakrun/vba_graph.py
**Note**: I've renamed the `office.py` back to `vba_graph`. After `hid emulation` will be added to drakvuf we can get rid of it.
> Add support for ppt,pttx,js,hta extensions

- drakrun/drakrun/sample_startup.py
> Fix handling vbs scripts

- drakrun/drakrun/main.py
> drakrun: Don't emit errors for broken samples

- drakrun/drakrun/draksetup.py
Don't merge until the domain is up.
> Change usage report domain

- drakcore/drakcore/process.py
- drakrun/drakrun/main.py
Reraise current exception for karton. This way, we can utilize
task restarting feature.
> drakrun, drakcore: Reraise exceptions for karton

- drakcore/debian/drakcore.install
- drakrun/debian/drakrun.install
> debian: Install systemd units to /lib/systemd

- drakrun/drakrun/draksetup.py
> drakrun: add root check before sanity test

- .github/workflows/debs.yml
This won't build at least for now. But it's a first step
> Hitting a bullseye - ci: Build release debs for bullseye

- docs/ipt.rst
- drakcore/drakcore/tools/ipt/drak-ipt-blocks.cpp
Previous version required guessing / looking into source code to know what arguments even exist.
Pinning argparse @ v2.9 due to https://github.com/p-ranav/argparse/issues/241.
> Improve drak-ipt-blocks argument parsing

- drakrun/drakrun/draksetup.py
spotted by @fabionitto in issue #759
> Fix typo in draksetup

- drakrun/drakrun/injector.py
- drakrun/drakrun/main.py
- test/test_sanity.py
> Fix injector timeouts

- .drone.yml
- drakrun/drakrun/injector.py
- drakrun/drakrun/main.py
- drakrun/requirements.txt
- test/test_sanity.py
Backport of https://github.com/CERT-Polska/drakvuf-sandbox/pull/749 to the older version of Drakvuf
> Backport: Fix injector timeouts for v0.18.x

- README.md
Most of the links at the top are obsolete or broken.
Sort and add missing contributors.
> Clean up the readme

- drakrun/drakrun/main.py
I don't think there's any reason to split them
> Combine config parsing and validation

- drakrun/drakrun/apiscout.py
- drakrun/drakrun/draksetup.py
- drakrun/drakrun/networking.py
- drakrun/drakrun/playground.py
A few small typing issues - by no means all of them, just making a small incremental improvement.
> Small typing improvements

- drakrun/drakrun/draksetup.py
and sorry for my premature push to master :face_in_clouds:
> Fix drakrun.lib.apiscout reference

- drakrun/drakrun/main.py
> Refactor drakvuf config to a single class

- README.md
> Add a discord link

- drakrun/drakrun/lib/sample_startup.py
> Fix: bug in get_startup_argv for MS Office files

- drakrun/drakrun/analyzer.py
- drakrun/requirements.txt
- Generate random filename when provided filename is not valid
- Append extension only if necessary
- Filename is validated using great [pathvalidate library](https://pypi.org/project/pathvalidate/)
> Fix: Proper filename validation

- .github/workflows/build.yml
- .github/workflows/release.yml
- docs/conf.py
- drakrun/drakrun/version.py
- drakrun/drakrun/web/frontend/package-lock.json
- drakrun/drakrun/web/frontend/package.json
- drakrun/setup.py
- scripts/bump_version.json
- test/conftest.py
Right now Python package name will stay "drakrun" tho...
> Rename package to 'drakvuf-sandbox'

- README.md
@psrok1 put insane amounts of effort into drakvuf recently, and listing him last doesn't do him justice.
The humble author of this PR sneakily uses this opportunity to put himself on the list too.
> Tweak the contributor order

- drakrun/drakrun/tools/get-explorer-pid.c
- When process is crashed/terminated, EPROCESS are left in kernel memory as long as there are open handles. We need to check if process object is non-signalled to choose only active processes.
- We're looking for native explorer.exe, not WoW64 one (closes https://github.com/CERT-Polska/drakvuf-sandbox/issues/809)
- And finally.. c'mon I now that this thing is a fork of libvmi example (https://github.com/libvmi/libvmi/blob/master/examples/process-list.c) but do we need all of these branches for Linux and FreeBSD? I don't think so.
> get-explorer-pid: Ignore terminated processes, WoW64 processes and remove non-Windows branches

- .github/workflows/build.yml
> CI: Bump upload-artifact/download-artifact to v4

- drakrun/drakrun/draksetup/main.py
- drakrun/drakrun/draksetup/vm_start.py
- drakrun/drakrun/draksetup/vm_stop.py
Starting and stopping a VM with all the network things and stuff. vm-1 is a default now.
> draksetup: vm-start/vm-stop

- Makefile
- drakrun/analyzer/analysis_options.py
- drakrun/analyzer/analyzer.py
- drakrun/analyzer/file_metadata.py
- drakrun/analyzer/worker.py
- drakrun/cli/main.py
- drakrun/cli/worker.py
- drakrun/data/config.toml
- drakrun/lib/config.py
- drakrun/lib/paths.py
- drakrun/web/analysis.py
- drakrun/web/analysis_list.py
- drakrun/web/app.py
- drakrun/web/frontend/src/AnalysisList.js
- drakrun/web/frontend/src/AnalysisMain.js
- drakrun/web/frontend/src/AnalysisStatus.js
- requirements.txt
- [https://github.com/rq/rq](rq-based) worker
- Integrated web part (mostly)
- Analysis are kept in `/var/lib/drakrun/analyses` for now
Known issues:
- we don't have initial PID information as we used to have from inject.log (we don't use injector when drakshell is active)
- not everything works for now :thinking: Current web needs to be modernized anyway...
> rq-based worker - first steps

- docs/conf.py
- drakrun/version.py
Just to mark another milestone in the development.
It will be better described in separate note pinned in the issues.
> Bump version: v0.19.0-alpha2

- drakrun/web/analysis.py
- drakrun/web/app.py
- drakrun/web/frontend/package-lock.json
- drakrun/web/frontend/package.json
- drakrun/web/frontend/src/AnalysisReport.jsx
- drakrun/web/frontend/src/AnalysisScreenshotViewer.jsx
Simple, zoomable screenshot viewer.
> web: Screenshot viewer

- drakrun/analyzer/postprocessing/process_tree.py
Execution of elevated process is delegated to a service, so PPID got from NtCreateUserProcess comes from some `svchost.exe`. 
The real PPID is then set via PS_ATTRIBUTE_PARENT_PROCESS, so further logs have the PPID of the real parent. If we spot this in logs, we rebind the PPID to the original process to show it in the correct place in process tree.
> Fix: handle changed PPID in case of elevation

- drakrun/web/api.py
- drakrun/web/frontend/src/AnalysisReport.jsx
- drakrun/web/storage.py
- Add correct Content-Disposition for download endpoints
- Add proper buttons to UI
> Feature: download pcap and dumps from web app

- drakrun/web/frontend/src/LogViewer.jsx
- LogViewer is now selectable
- JSON inspector works also when search field is used and part of the line is highlighted
- Solved race condition when log source/filter was changed but previous logs were still loading
> Fix: various issues in LogViewer

- drakrun/analyzer/postprocessing/plugins/capa_plugin/capa_processor.py
In the following cases, ttps.json can't be generated due to too strict validation:
- hooks.txt in `apimon` that contains hooks for argumentless functions in which case `Arguments` key is missing. That kind of JSON is unaccepted by https://github.com/mandiant/capa/blob/master/capa/features/extractors/drakvuf/models.py#L71
- `syscalls` from newer Drakvuf versions that may include "FromParentModule" and "FromModule" keys with `null` as a value which is unaccepted by https://github.com/mandiant/capa/blob/master/capa/features/extractors/drakvuf/models.py#L85
> Fix: dirty fix for too strict CAPA validation

- drakrun/web/storage.py
Don't try to use s3 when it's disabled
> Fix: add missing else clause in s3 handling
